#include<iostream.h>
#include<conio.h>
#include<string.h>
void main()
{
   char s1[100];
   cout<<"\n enter information=";
   cin>>s1;
   {
      cout<<strrev(s1)<<" ";
   }

getch();
}
++++++++++++++++***************++++++++++++++++++****************+++++++++++++

#include<iostream.h>
#include<conio.h>
#include<string.h>
void main()
{

   char s1[100],s2[100];
   cout<<"\n enter 1st information=";
   cin>>s1;
   cout<<"\n enter 2nd information=";
   cin>>s2;
   cout<<"\n before copy \n";
   cout<<s1<<" ";
   cout<<s2<<" ";
   cout<<"\n after copy \n";
   cout<<s1<<" ";
   cout<<s2<<" ";
getch();
}
